### ISSUE TITLE
VAP: Verified or Validated ?

### ISSUE THREAD

**Issue by tanneberger** [QratorLabs/ASPA#20]
There is inconsistent wording in the different drafts:

In the [aspa-profile-draft](https://datatracker.ietf.org/doc/html/draft-ietf-sidrops-aspa-profile-17) VAP stands for **validated** aspa payload, where in the [aspa-verification-draft](https://datatracker.ietf.org/doc/draft-ietf-sidrops-aspa-verification/) it stands for **verified** aspa payload. 

Which of the two versions is preferred? 

@job @ksriram2

**Comment by job** [comment]
I think this is the goal: We speak about **validation** in context of processing the RPKI ASPA object (cryptographic validation etc), and **verification** in context of the BGP UPDATE messages (rejecting BGP route announcements that are ASPA-invalid)

**Comment by tanneberger** [comment]
Just to clarify, there are different terms for the same definition: 

In the aspa-profile draft: " In addition, the procedures for verifying AS_PATHs in BGP UPDATE messages using Validated ASPA Payloads (VAPs) are described in that document." 
VAP = Validated ASPA Payload

In the aspa-verification draft: "Verified ASPA Payload (VAP) refers to the payload in a cryptographically verified: 
VAP = Verified ASPA Payload

**Comment by job** [comment]
Yup, I think the aspa-verification document should change "Verified ASPA Payload" to "Validated ASPA Payload"

**Comment by job** [comment]
Fixed in https://github.com/QratorLabs/ASPA/commit/c9f4df6f2095a32f3dfac15e2916dd2d9406f0c3
